name: Matrix Demo
on:
  push:
    branches:
      - 'dev-*'
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12,14,16]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system}}
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install Nodejs
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version}}
      - name: Install Dependencies
        run: npm ci
      - name: Buold project
        run: npm run build

