name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deloyable artifact files
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact-name}}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying and uploading..."
        